#cloud-config
autoinstall:
  version: 1
  locale: de_DE #Sprache
  keyboard: #Tastaturbelegung
    layout: de 
    variant: ''
  network: #Netzwerkkonfiguration
    network:
      version: 2
      ethernets:
        enp3s0:
          dhcp4: true
  identity: #Hostname, Benutzername und Passwort
    hostname: ubuntu-desktop
    username: cttest
    password: $crypted_pass #
  ssh: #SSH Konfiguration. Hier wird der SSH-Server installiert und Login mit Passwort erlaubt.
    install-server: true
    allow-pw: true
  storage: #Partitionierung: Achtung, hier wird die gesamte Festplatte genutzt.
    layout:
      name: lvm    
  #apt: #Paketquellen
  #  geoip: true
  #  preserve_sources_list: false
  #  primary:
  #  - arches: [amd64, i386]
  #    uri: http://de.archive.ubuntu.com/ubuntu/
  packages: # zu installierende Debian-Pakete
    - btop
    - librefoffice
  snaps: #zu installierende Snap-Pakete
    - name: multipass
      channel: latest/stable
      classic: true
  timezone: Europe/Berlin #Zeitzone
